Nguyen
han8129/SE2_Markdown-Editor pull request #8
Opened 2024-03-16 15:00 UTC by theornguyn

2024-03-16 18:14 UTC, han8129 requested changes
Dù page đã render đúng như miêu tả, nhưng code này là
là copy y nguyên, không có loại bỏ đi các tags + script
thừa. Cần xóa đi để việc sửa và thêm các tính năng
dễ dàng hơn

2024-03-16 18:14 UTC, han8129 commented on src/main/resources/templates/UI.html
> +
Không cần dùng đến

2024-03-16 18:14 UTC, han8129 commented on src/main/resources/static/css/UI.css
chưa cần đến custom css như này, mà hãy import stylesheet `../static/bootstrap.min.css`
và sử dụng
```html
<nav class="col-2">...</nav>
<textarea class="col-5">...</textarea> 
<div class="col-5">...</div> 
```
chi tiết về [column layout của bootstrap](https://getbootstrap.com/docs/5.2/layout/columns/#how-they-work)

2024-03-16 18:20 UTC, theornguyn commented
t đã nhận được yêu cầu

On Sun, 17 Mar 2024 at 01:14 Vũ Nhật Hoàng ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Dù page đã render đúng như miêu tả, nhưng code này là
> là copy y nguyên, không có loại bỏ đi các tags + script
> thừa. Cần xóa đi để việc sửa và thêm các tính năng
> dễ dàng hơn
> ------------------------------
>
> In src/main/resources/templates/UI.html
> <https://github.com/han8129/SE2_Markdown-Editor/pull/8#discussion_r1527210265>
> :
>
> > +    <!-- Include Mermaid library -->
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.0/mermaid.min.js"></script>
> +    <!-- Initialize Mermaid -->
> +    <script>mermaid.initialize({startOnLoad:true});</script>
> +    <!-- Include KaTeX library -->
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js"></script>
> +    <!-- Include KaTeX CSS -->
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css">
> +    <!-- Include the auto-render extension for KaTeX -->
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js"></script>
> +    <!-- Initialize KaTeX auto-render -->
> +    <script>document.addEventListener("DOMContentLoaded", function(){ renderMathInElement(document.body); });</script>
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.0.9/purify.min.js"></script>
> +    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js" defer></script>
> +    <script src="../static/js/UI.js" defer></script>
> +
>
> Không cần dùng đến
> ------------------------------
>
> On src/main/resources/static/css/UI.css
> <https://github.com/han8129/SE2_Markdown-Editor/pull/8#discussion_r1527211129>
> :
>
> chưa cần đến custom css như này, mà hãy import stylesheet
> ../static/bootstrap.min.css
> và sử dụng
>
> <nav class="col-2">...</nav><textarea class="col-5">...</textarea> <div class="col-5">...</div>
>
> chi tiết về column layout của bootstrap
> <https://getbootstrap.com/docs/5.2/layout/columns/#how-they-work>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/han8129/SE2_Markdown-Editor/pull/8#pullrequestreview-1941262031>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BG75RN6QKG567AM7NFCH2Q3YYSDYVAVCNFSM6AAAAABEZMEXNKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBRGI3DEMBTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-04-23 08:11 UTC, han8129 approved these changes

2024-04-23 08:11 UTC, han8129 commented on src/main/resources/static/js/UI.js
> +    });
đoạn này không có tác dụng gì đâu, hay bỏ đi

2024-04-23 08:17 UTC, merged