Implement Sidebar Template
han8129/SE2_Markdown-Editor pull request #9
Opened 2024-03-17 10:33 UTC by Mydear1230

2024-03-19 05:22 UTC, han8129 requested changes
Dù code đã hiển thị được theo yêu cầu của tôi, nhưng còn nhiều import không được sử dụng đến. Cần xóa đi các import đó, để khi bạn khác chỉnh lại sẽ dễ dàng, và đặc biệt là
hạn chế việc Styling bị override bởi các thư viên được import

Các icon trong code thì sẽ sử dụng từ thư viện [Folk-Awesome](https://forkaweso.me/Fork-Awesome/icons/)
```html
<head>
<link rel="stylesheet" href="../static/css/fork-awesome.min.css">
</head>
<body>
<i class="fa fa-trash" aria-hidden="true">
</body>
```

2024-03-19 05:22 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
bootstrap đã đc bao gồm trong thư mục `static/js`, bạn hãy thay thế vào. Tuy nhiên tôi đang dùng Bootstrap v5.2
syntax có thể sẽ khác

2024-03-19 05:22 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
Nên xóa đi. Dù tôi khuyến khích việc sử dụng bootstrap, nhưng mà trong page này thì bạn không sử
dụng đến bất kỳ styling nào của Bootstrap

2024-03-19 05:22 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +                    <li><a href="#"><i class="glyphicon glyphicon-cog"></i> Setting</a></li>
Với các icon chúng ta sẽ sử dụng [Fork-Awensome](https://forkaweso.me/Fork-Awesome/icons/) nhé
VD: `<i class="glyphicon glyphicon-trash">` -> `<i class="fa fa-trash" aria-hidden="true">`

2024-03-19 05:22 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.css
> +@import url('https://fonts.googleapis.com/css2?family=Crimson+Pro&family=Literata'
Không nên sử dụng các import mà cần Internet như này nhé, hơn nữa
mình chưa cần quan tâm đến font

2024-04-09 06:50 UTC, han8129 requested changes
các vấn đề từ review trước vẫn còn ở đó, và cần update lại nhánh này với
update mới nhất ở nhóm develop

2024-04-09 06:50 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymo
tất cả các file này đã được bao gồm trong project ở resource/static /css và resources/static/js

2024-04-09 06:50 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css" integrity="sha256-XoaMnoYC5TH6/+ihMEnospgm0J1PM/nioxbOUdnM8HY=" crossorigin="anonymous">
đã bao gồm tại resources/static/css tại develop, hãy sử dụng nó, không import trên mạng

2024-04-09 06:50 UTC, han8129 commented on src/main/resources/templates/sidebar/sidebar.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymo
import này không có tác dụng gì cả, hãy bỏ nó đi

2024-04-13 19:25 UTC, Mydear1230 commented
Tôi đã update

2024-04-23 08:07 UTC, han8129 commented
Đã hoàn thành

2024-04-23 08:08 UTC, merged